apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  ports:
    - name: 9200tcp02
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: 9300tcp02
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
